// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: spell.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Ankama.Dofus.Server.Game.Protocol.Spell {

  /// <summary>Holder for reflection information generated from spell.proto</summary>
  public static partial class SpellReflection {

    #region Descriptor
    /// <summary>File descriptor for spell.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpellReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtzcGVsbC5wcm90bxIrY29tLmFua2FtYS5kb2Z1cy5zZXJ2ZXIuZ2FtZS5w",
            "cm90b2NvbC5zcGVsbBoMY29tbW9uLnByb3RvIjEKHVNwZWxsVmFyaWFudEFj",
            "dGl2YXRpb25SZXF1ZXN0EhAKCHNwZWxsX2lkGAEgASgFIuEBCh1Gb3JnZXR0",
            "YWJsZVNwZWxsQWN0aW9uUmVxdWVzdBIQCghzcGVsbF9pZBgBIAEoBRJxCgZh",
            "Y3Rpb24YAiABKA4yYS5jb20uYW5rYW1hLmRvZnVzLnNlcnZlci5nYW1lLnBy",
            "b3RvY29sLnNwZWxsLkZvcmdldHRhYmxlU3BlbGxBY3Rpb25SZXF1ZXN0LkZv",
            "cmdldHRhYmxlU3BlbGxBY3Rpb24iOwoWRm9yZ2V0dGFibGVTcGVsbEFjdGlv",
            "bhIKCgZGT1JHRVQQABIJCgVFUVVJUBABEgoKBlJFTU9WRRACInoKF0FwcGx5",
            "U3BlbGxNb2RpZmllckV2ZW50EhAKCGFjdG9yX2lkGAEgASgDEk0KCG1vZGlm",
            "aWVyGAIgASgLMjsuY29tLmFua2FtYS5kb2Z1cy5zZXJ2ZXIuZ2FtZS5wcm90",
            "b2NvbC5jb21tb24uU3BlbGxNb2RpZmllciLyAQoYUmVtb3ZlU3BlbGxNb2Rp",
            "ZmllckV2ZW50EhAKCGFjdG9yX2lkGAEgASgDEloKC2FjdGlvbl90eXBlGAIg",
            "ASgOMkUuY29tLmFua2FtYS5kb2Z1cy5zZXJ2ZXIuZ2FtZS5wcm90b2NvbC5j",
            "b21tb24uU3BlbGxNb2RpZmllckFjdGlvblR5cGUSVgoNbW9kaWZpZXJfdHlw",
            "ZRgDIAEoDjI/LmNvbS5hbmthbWEuZG9mdXMuc2VydmVyLmdhbWUucHJvdG9j",
            "b2wuY29tbW9uLlNwZWxsTW9kaWZpZXJUeXBlEhAKCHNwZWxsX2lkGAQgASgF",
            "IkIKG1NwZWxsVmFyaWFudEFjdGl2YXRpb25FdmVudBIQCghzcGVsbF9pZBgB",
            "IAEoBRIRCgllZmZlY3RpdmUYAiABKAgiNwojRm9yZ2V0dGFibGVTcGVsbEVx",
            "dWlwbWVudFNsb3RzRXZlbnQSEAoIcXVhbnRpdHkYASABKAUigAIKHUZvcmdl",
            "dHRhYmxlU3BlbGxEZWxldGlvbkV2ZW50EmkKBnJlYXNvbhgBIAEoDjJZLmNv",
            "bS5hbmthbWEuZG9mdXMuc2VydmVyLmdhbWUucHJvdG9jb2wuc3BlbGwuRm9y",
            "Z2V0dGFibGVTcGVsbERlbGV0aW9uRXZlbnQuRGVsZXRpb25SZWFzb24SDgoG",
            "c3BlbGxzGAIgAygFImQKDkRlbGV0aW9uUmVhc29uEgsKB1VOS05PV04QABIZ",
            "ChVBRE1JTl9DT01NQU5EX1JFUVVFU1QQARINCglGT1JHT1RURU4QAhIMCghE",
            "SVNBQkxFRBADEg0KCU5PVF9GT1VORBAEIuABChZGb3JnZXR0YWJsZVNwZWxs",
            "c0V2ZW50EloKBmFjdGlvbhgBIAEoDjJKLmNvbS5hbmthbWEuZG9mdXMuc2Vy",
            "dmVyLmdhbWUucHJvdG9jb2wuc3BlbGwuRm9yZ2V0dGFibGVTcGVsbHNFdmVu",
            "dC5BY3Rpb24SRgoGc3BlbGxzGAIgAygLMjYuY29tLmFua2FtYS5kb2Z1cy5z",
            "ZXJ2ZXIuZ2FtZS5wcm90b2NvbC5zcGVsbC5TcGVsbEl0ZW0iIgoGQWN0aW9u",
            "EgwKCERJU1BBVENIEAASCgoGVVBEQVRFEAEixwEKC1NwZWxsc0V2ZW50EhsK",
            "E3NwZWxsX3Zpc3VhbGlzYXRpb24YASABKAgSTAoMaHVtYW5fc3BlbGxzGAIg",
            "AygLMjYuY29tLmFua2FtYS5kb2Z1cy5zZXJ2ZXIuZ2FtZS5wcm90b2NvbC5z",
            "cGVsbC5TcGVsbEl0ZW0STQoNbXV0YW50X3NwZWxscxgDIAMoCzI2LmNvbS5h",
            "bmthbWEuZG9mdXMuc2VydmVyLmdhbWUucHJvdG9jb2wuc3BlbGwuU3BlbGxJ",
            "dGVtIlgKCVNwZWxsSXRlbRIQCghzcGVsbF9pZBgBIAEoBRITCgtzcGVsbF9s",
            "ZXZlbBgCIAEoBRIWCglhdmFpbGFibGUYAyABKAhIAIgBAUIMCgpfYXZhaWxh",
            "YmxlQg9aDXByb3RvY29sL2dhbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Ankama.Dofus.Server.Game.Protocol.Common.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellVariantActivationRequest), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellVariantActivationRequest.Parser, new[]{ "SpellId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Parser, new[]{ "SpellId", "Action" }, null, new[]{ typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ApplySpellModifierEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ApplySpellModifierEvent.Parser, new[]{ "ActorId", "Modifier" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.RemoveSpellModifierEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.RemoveSpellModifierEvent.Parser, new[]{ "ActorId", "ActionType", "ModifierType", "SpellId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellVariantActivationEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellVariantActivationEvent.Parser, new[]{ "SpellId", "Effective" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellEquipmentSlotsEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellEquipmentSlotsEvent.Parser, new[]{ "Quantity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Parser, new[]{ "Reason", "Spells" }, null, new[]{ typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Parser, new[]{ "Action", "Spells" }, null, new[]{ typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellsEvent), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellsEvent.Parser, new[]{ "SpellVisualisation", "HumanSpells", "MutantSpells" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem), global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem.Parser, new[]{ "SpellId", "SpellLevel", "Available" }, new[]{ "Available" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpellVariantActivationRequest : pb::IMessage<SpellVariantActivationRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpellVariantActivationRequest> _parser = new pb::MessageParser<SpellVariantActivationRequest>(() => new SpellVariantActivationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpellVariantActivationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationRequest(SpellVariantActivationRequest other) : this() {
      spellId_ = other.spellId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationRequest Clone() {
      return new SpellVariantActivationRequest(this);
    }

    /// <summary>Field number for the "spell_id" field.</summary>
    public const int SpellIdFieldNumber = 1;
    private int spellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellId {
      get { return spellId_; }
      set {
        spellId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpellVariantActivationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpellVariantActivationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpellId != other.SpellId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpellId != 0) hash ^= SpellId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpellVariantActivationRequest other) {
      if (other == null) {
        return;
      }
      if (other.SpellId != 0) {
        SpellId = other.SpellId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ForgettableSpellActionRequest : pb::IMessage<ForgettableSpellActionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForgettableSpellActionRequest> _parser = new pb::MessageParser<ForgettableSpellActionRequest>(() => new ForgettableSpellActionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForgettableSpellActionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellActionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellActionRequest(ForgettableSpellActionRequest other) : this() {
      spellId_ = other.spellId_;
      action_ = other.action_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellActionRequest Clone() {
      return new ForgettableSpellActionRequest(this);
    }

    /// <summary>Field number for the "spell_id" field.</summary>
    public const int SpellIdFieldNumber = 1;
    private int spellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellId {
      get { return spellId_; }
      set {
        spellId_ = value;
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction action_ = global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForgettableSpellActionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForgettableSpellActionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpellId != other.SpellId) return false;
      if (Action != other.Action) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpellId != 0) hash ^= SpellId.GetHashCode();
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellId);
      }
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForgettableSpellActionRequest other) {
      if (other == null) {
        return;
      }
      if (other.SpellId != 0) {
        SpellId = other.SpellId;
      }
      if (other.Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction.Forget) {
        Action = other.Action;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            Action = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            Action = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellActionRequest.Types.ForgettableSpellAction) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ForgettableSpellActionRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ForgettableSpellAction {
        [pbr::OriginalName("FORGET")] Forget = 0,
        [pbr::OriginalName("EQUIP")] Equip = 1,
        [pbr::OriginalName("REMOVE")] Remove = 2,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApplySpellModifierEvent : pb::IMessage<ApplySpellModifierEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApplySpellModifierEvent> _parser = new pb::MessageParser<ApplySpellModifierEvent>(() => new ApplySpellModifierEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApplySpellModifierEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplySpellModifierEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplySpellModifierEvent(ApplySpellModifierEvent other) : this() {
      actorId_ = other.actorId_;
      modifier_ = other.modifier_ != null ? other.modifier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplySpellModifierEvent Clone() {
      return new ApplySpellModifierEvent(this);
    }

    /// <summary>Field number for the "actor_id" field.</summary>
    public const int ActorIdFieldNumber = 1;
    private long actorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    /// <summary>Field number for the "modifier" field.</summary>
    public const int ModifierFieldNumber = 2;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifier modifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifier Modifier {
      get { return modifier_; }
      set {
        modifier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApplySpellModifierEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApplySpellModifierEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActorId != other.ActorId) return false;
      if (!object.Equals(Modifier, other.Modifier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActorId != 0L) hash ^= ActorId.GetHashCode();
      if (modifier_ != null) hash ^= Modifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActorId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActorId);
      }
      if (modifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Modifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActorId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActorId);
      }
      if (modifier_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Modifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (modifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Modifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApplySpellModifierEvent other) {
      if (other == null) {
        return;
      }
      if (other.ActorId != 0L) {
        ActorId = other.ActorId;
      }
      if (other.modifier_ != null) {
        if (modifier_ == null) {
          Modifier = new global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifier();
        }
        Modifier.MergeFrom(other.Modifier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActorId = input.ReadInt64();
            break;
          }
          case 18: {
            if (modifier_ == null) {
              Modifier = new global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifier();
            }
            input.ReadMessage(Modifier);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActorId = input.ReadInt64();
            break;
          }
          case 18: {
            if (modifier_ == null) {
              Modifier = new global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifier();
            }
            input.ReadMessage(Modifier);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RemoveSpellModifierEvent : pb::IMessage<RemoveSpellModifierEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RemoveSpellModifierEvent> _parser = new pb::MessageParser<RemoveSpellModifierEvent>(() => new RemoveSpellModifierEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RemoveSpellModifierEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoveSpellModifierEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoveSpellModifierEvent(RemoveSpellModifierEvent other) : this() {
      actorId_ = other.actorId_;
      actionType_ = other.actionType_;
      modifierType_ = other.modifierType_;
      spellId_ = other.spellId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoveSpellModifierEvent Clone() {
      return new RemoveSpellModifierEvent(this);
    }

    /// <summary>Field number for the "actor_id" field.</summary>
    public const int ActorIdFieldNumber = 1;
    private long actorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ActorId {
      get { return actorId_; }
      set {
        actorId_ = value;
      }
    }

    /// <summary>Field number for the "action_type" field.</summary>
    public const int ActionTypeFieldNumber = 2;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType actionType_ = global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "modifier_type" field.</summary>
    public const int ModifierTypeFieldNumber = 3;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType modifierType_ = global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType ModifierType {
      get { return modifierType_; }
      set {
        modifierType_ = value;
      }
    }

    /// <summary>Field number for the "spell_id" field.</summary>
    public const int SpellIdFieldNumber = 4;
    private int spellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellId {
      get { return spellId_; }
      set {
        spellId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RemoveSpellModifierEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RemoveSpellModifierEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActorId != other.ActorId) return false;
      if (ActionType != other.ActionType) return false;
      if (ModifierType != other.ModifierType) return false;
      if (SpellId != other.SpellId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ActorId != 0L) hash ^= ActorId.GetHashCode();
      if (ActionType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid) hash ^= ActionType.GetHashCode();
      if (ModifierType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification) hash ^= ModifierType.GetHashCode();
      if (SpellId != 0) hash ^= SpellId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActorId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActorId);
      }
      if (ActionType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ActionType);
      }
      if (ModifierType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ModifierType);
      }
      if (SpellId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SpellId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActorId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ActorId);
      }
      if (ActionType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ActionType);
      }
      if (ModifierType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ModifierType);
      }
      if (SpellId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SpellId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ActorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ActorId);
      }
      if (ActionType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionType);
      }
      if (ModifierType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ModifierType);
      }
      if (SpellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RemoveSpellModifierEvent other) {
      if (other == null) {
        return;
      }
      if (other.ActorId != 0L) {
        ActorId = other.ActorId;
      }
      if (other.ActionType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType.ActionInvalid) {
        ActionType = other.ActionType;
      }
      if (other.ModifierType != global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType.InvalidModification) {
        ModifierType = other.ModifierType;
      }
      if (other.SpellId != 0) {
        SpellId = other.SpellId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActorId = input.ReadInt64();
            break;
          }
          case 16: {
            ActionType = (global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType) input.ReadEnum();
            break;
          }
          case 24: {
            ModifierType = (global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType) input.ReadEnum();
            break;
          }
          case 32: {
            SpellId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ActorId = input.ReadInt64();
            break;
          }
          case 16: {
            ActionType = (global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierActionType) input.ReadEnum();
            break;
          }
          case 24: {
            ModifierType = (global::Com.Ankama.Dofus.Server.Game.Protocol.Common.SpellModifierType) input.ReadEnum();
            break;
          }
          case 32: {
            SpellId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpellVariantActivationEvent : pb::IMessage<SpellVariantActivationEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpellVariantActivationEvent> _parser = new pb::MessageParser<SpellVariantActivationEvent>(() => new SpellVariantActivationEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpellVariantActivationEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationEvent(SpellVariantActivationEvent other) : this() {
      spellId_ = other.spellId_;
      effective_ = other.effective_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellVariantActivationEvent Clone() {
      return new SpellVariantActivationEvent(this);
    }

    /// <summary>Field number for the "spell_id" field.</summary>
    public const int SpellIdFieldNumber = 1;
    private int spellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellId {
      get { return spellId_; }
      set {
        spellId_ = value;
      }
    }

    /// <summary>Field number for the "effective" field.</summary>
    public const int EffectiveFieldNumber = 2;
    private bool effective_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Effective {
      get { return effective_; }
      set {
        effective_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpellVariantActivationEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpellVariantActivationEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpellId != other.SpellId) return false;
      if (Effective != other.Effective) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpellId != 0) hash ^= SpellId.GetHashCode();
      if (Effective != false) hash ^= Effective.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (Effective != false) {
        output.WriteRawTag(16);
        output.WriteBool(Effective);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (Effective != false) {
        output.WriteRawTag(16);
        output.WriteBool(Effective);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellId);
      }
      if (Effective != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpellVariantActivationEvent other) {
      if (other == null) {
        return;
      }
      if (other.SpellId != 0) {
        SpellId = other.SpellId;
      }
      if (other.Effective != false) {
        Effective = other.Effective;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            Effective = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            Effective = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ForgettableSpellEquipmentSlotsEvent : pb::IMessage<ForgettableSpellEquipmentSlotsEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForgettableSpellEquipmentSlotsEvent> _parser = new pb::MessageParser<ForgettableSpellEquipmentSlotsEvent>(() => new ForgettableSpellEquipmentSlotsEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForgettableSpellEquipmentSlotsEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellEquipmentSlotsEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellEquipmentSlotsEvent(ForgettableSpellEquipmentSlotsEvent other) : this() {
      quantity_ = other.quantity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellEquipmentSlotsEvent Clone() {
      return new ForgettableSpellEquipmentSlotsEvent(this);
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 1;
    private int quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForgettableSpellEquipmentSlotsEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForgettableSpellEquipmentSlotsEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Quantity != other.Quantity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Quantity != 0) hash ^= Quantity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Quantity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Quantity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Quantity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Quantity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Quantity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForgettableSpellEquipmentSlotsEvent other) {
      if (other == null) {
        return;
      }
      if (other.Quantity != 0) {
        Quantity = other.Quantity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Quantity = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Quantity = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ForgettableSpellDeletionEvent : pb::IMessage<ForgettableSpellDeletionEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForgettableSpellDeletionEvent> _parser = new pb::MessageParser<ForgettableSpellDeletionEvent>(() => new ForgettableSpellDeletionEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForgettableSpellDeletionEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellDeletionEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellDeletionEvent(ForgettableSpellDeletionEvent other) : this() {
      reason_ = other.reason_;
      spells_ = other.spells_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellDeletionEvent Clone() {
      return new ForgettableSpellDeletionEvent(this);
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 1;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason reason_ = global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "spells" field.</summary>
    public const int SpellsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_spells_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> spells_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Spells {
      get { return spells_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForgettableSpellDeletionEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForgettableSpellDeletionEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reason != other.Reason) return false;
      if(!spells_.Equals(other.spells_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Reason != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown) hash ^= Reason.GetHashCode();
      hash ^= spells_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reason != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      spells_.WriteTo(output, _repeated_spells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reason != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Reason);
      }
      spells_.WriteTo(ref output, _repeated_spells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Reason != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      size += spells_.CalculateSize(_repeated_spells_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForgettableSpellDeletionEvent other) {
      if (other == null) {
        return;
      }
      if (other.Reason != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason.Unknown) {
        Reason = other.Reason;
      }
      spells_.Add(other.spells_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reason = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            spells_.AddEntriesFrom(input, _repeated_spells_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Reason = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellDeletionEvent.Types.DeletionReason) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            spells_.AddEntriesFrom(ref input, _repeated_spells_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ForgettableSpellDeletionEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum DeletionReason {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("ADMIN_COMMAND_REQUEST")] AdminCommandRequest = 1,
        [pbr::OriginalName("FORGOTTEN")] Forgotten = 2,
        [pbr::OriginalName("DISABLED")] Disabled = 3,
        [pbr::OriginalName("NOT_FOUND")] NotFound = 4,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ForgettableSpellsEvent : pb::IMessage<ForgettableSpellsEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForgettableSpellsEvent> _parser = new pb::MessageParser<ForgettableSpellsEvent>(() => new ForgettableSpellsEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForgettableSpellsEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellsEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellsEvent(ForgettableSpellsEvent other) : this() {
      action_ = other.action_;
      spells_ = other.spells_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForgettableSpellsEvent Clone() {
      return new ForgettableSpellsEvent(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action action_ = global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "spells" field.</summary>
    public const int SpellsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> _repeated_spells_codec
        = pb::FieldCodec.ForMessage(18, global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem.Parser);
    private readonly pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> spells_ = new pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> Spells {
      get { return spells_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForgettableSpellsEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForgettableSpellsEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if(!spells_.Equals(other.spells_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch) hash ^= Action.GetHashCode();
      hash ^= spells_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      spells_.WriteTo(output, _repeated_spells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      spells_.WriteTo(ref output, _repeated_spells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      size += spells_.CalculateSize(_repeated_spells_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForgettableSpellsEvent other) {
      if (other == null) {
        return;
      }
      if (other.Action != global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action.Dispatch) {
        Action = other.Action;
      }
      spells_.Add(other.spells_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Action = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action) input.ReadEnum();
            break;
          }
          case 18: {
            spells_.AddEntriesFrom(input, _repeated_spells_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Action = (global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.ForgettableSpellsEvent.Types.Action) input.ReadEnum();
            break;
          }
          case 18: {
            spells_.AddEntriesFrom(ref input, _repeated_spells_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ForgettableSpellsEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Action {
        [pbr::OriginalName("DISPATCH")] Dispatch = 0,
        [pbr::OriginalName("UPDATE")] Update = 1,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpellsEvent : pb::IMessage<SpellsEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpellsEvent> _parser = new pb::MessageParser<SpellsEvent>(() => new SpellsEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpellsEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellsEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellsEvent(SpellsEvent other) : this() {
      spellVisualisation_ = other.spellVisualisation_;
      humanSpells_ = other.humanSpells_.Clone();
      mutantSpells_ = other.mutantSpells_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellsEvent Clone() {
      return new SpellsEvent(this);
    }

    /// <summary>Field number for the "spell_visualisation" field.</summary>
    public const int SpellVisualisationFieldNumber = 1;
    private bool spellVisualisation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SpellVisualisation {
      get { return spellVisualisation_; }
      set {
        spellVisualisation_ = value;
      }
    }

    /// <summary>Field number for the "human_spells" field.</summary>
    public const int HumanSpellsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> _repeated_humanSpells_codec
        = pb::FieldCodec.ForMessage(18, global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem.Parser);
    private readonly pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> humanSpells_ = new pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> HumanSpells {
      get { return humanSpells_; }
    }

    /// <summary>Field number for the "mutant_spells" field.</summary>
    public const int MutantSpellsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> _repeated_mutantSpells_codec
        = pb::FieldCodec.ForMessage(26, global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem.Parser);
    private readonly pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> mutantSpells_ = new pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellItem> MutantSpells {
      get { return mutantSpells_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpellsEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpellsEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpellVisualisation != other.SpellVisualisation) return false;
      if(!humanSpells_.Equals(other.humanSpells_)) return false;
      if(!mutantSpells_.Equals(other.mutantSpells_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpellVisualisation != false) hash ^= SpellVisualisation.GetHashCode();
      hash ^= humanSpells_.GetHashCode();
      hash ^= mutantSpells_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpellVisualisation != false) {
        output.WriteRawTag(8);
        output.WriteBool(SpellVisualisation);
      }
      humanSpells_.WriteTo(output, _repeated_humanSpells_codec);
      mutantSpells_.WriteTo(output, _repeated_mutantSpells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpellVisualisation != false) {
        output.WriteRawTag(8);
        output.WriteBool(SpellVisualisation);
      }
      humanSpells_.WriteTo(ref output, _repeated_humanSpells_codec);
      mutantSpells_.WriteTo(ref output, _repeated_mutantSpells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpellVisualisation != false) {
        size += 1 + 1;
      }
      size += humanSpells_.CalculateSize(_repeated_humanSpells_codec);
      size += mutantSpells_.CalculateSize(_repeated_mutantSpells_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpellsEvent other) {
      if (other == null) {
        return;
      }
      if (other.SpellVisualisation != false) {
        SpellVisualisation = other.SpellVisualisation;
      }
      humanSpells_.Add(other.humanSpells_);
      mutantSpells_.Add(other.mutantSpells_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpellVisualisation = input.ReadBool();
            break;
          }
          case 18: {
            humanSpells_.AddEntriesFrom(input, _repeated_humanSpells_codec);
            break;
          }
          case 26: {
            mutantSpells_.AddEntriesFrom(input, _repeated_mutantSpells_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpellVisualisation = input.ReadBool();
            break;
          }
          case 18: {
            humanSpells_.AddEntriesFrom(ref input, _repeated_humanSpells_codec);
            break;
          }
          case 26: {
            mutantSpells_.AddEntriesFrom(ref input, _repeated_mutantSpells_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SpellItem : pb::IMessage<SpellItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpellItem> _parser = new pb::MessageParser<SpellItem>(() => new SpellItem());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpellItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Ankama.Dofus.Server.Game.Protocol.Spell.SpellReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellItem(SpellItem other) : this() {
      _hasBits0 = other._hasBits0;
      spellId_ = other.spellId_;
      spellLevel_ = other.spellLevel_;
      available_ = other.available_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpellItem Clone() {
      return new SpellItem(this);
    }

    /// <summary>Field number for the "spell_id" field.</summary>
    public const int SpellIdFieldNumber = 1;
    private int spellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellId {
      get { return spellId_; }
      set {
        spellId_ = value;
      }
    }

    /// <summary>Field number for the "spell_level" field.</summary>
    public const int SpellLevelFieldNumber = 2;
    private int spellLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SpellLevel {
      get { return spellLevel_; }
      set {
        spellLevel_ = value;
      }
    }

    /// <summary>Field number for the "available" field.</summary>
    public const int AvailableFieldNumber = 3;
    private readonly static bool AvailableDefaultValue = false;

    private bool available_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Available {
      get { if ((_hasBits0 & 1) != 0) { return available_; } else { return AvailableDefaultValue; } }
      set {
        _hasBits0 |= 1;
        available_ = value;
      }
    }
    /// <summary>Gets whether the "available" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvailable {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "available" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvailable() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpellItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpellItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpellId != other.SpellId) return false;
      if (SpellLevel != other.SpellLevel) return false;
      if (Available != other.Available) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpellId != 0) hash ^= SpellId.GetHashCode();
      if (SpellLevel != 0) hash ^= SpellLevel.GetHashCode();
      if (HasAvailable) hash ^= Available.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (SpellLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SpellLevel);
      }
      if (HasAvailable) {
        output.WriteRawTag(24);
        output.WriteBool(Available);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpellId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SpellId);
      }
      if (SpellLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SpellLevel);
      }
      if (HasAvailable) {
        output.WriteRawTag(24);
        output.WriteBool(Available);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellId);
      }
      if (SpellLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SpellLevel);
      }
      if (HasAvailable) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpellItem other) {
      if (other == null) {
        return;
      }
      if (other.SpellId != 0) {
        SpellId = other.SpellId;
      }
      if (other.SpellLevel != 0) {
        SpellLevel = other.SpellLevel;
      }
      if (other.HasAvailable) {
        Available = other.Available;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            SpellLevel = input.ReadInt32();
            break;
          }
          case 24: {
            Available = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpellId = input.ReadInt32();
            break;
          }
          case 16: {
            SpellLevel = input.ReadInt32();
            break;
          }
          case 24: {
            Available = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
